WIP
platogo/cordova-screenshot pull request #3
Opened 2024-04-03 07:18 UTC by attilakiss323

2024-04-09 12:54 UTC, majeed-platogo requested changes
Since permission is no longer need on android you need to remove [this](https://github.com/platogo/cordova-screenshot/blob/f65e641cd2178d7a56d36051065571dc6712a6f2/src/android/Screenshot.java#L73)

2024-04-12 13:05 UTC, dmitry-platogo commented on src/android/ScreenshotSaver.java
> +import static com.xtreme.plugins.XtremePushPlugin.TAG;
Could you please clarify, why do we need this line? and how does XtremePushPlugin connected to it?

Shouldn't we just define Tag here as smth like:
```
public class ScreenshotSaver {
  private static final String TAG = "ScreenshotSaver";
```

2024-04-15 11:37 UTC, dmitry-platogo approved these changes
I was able to see screenshots in the app after this fix, great job @attilakiss323

2024-04-16 07:53 UTC, majeed-platogo requested changes
@attilakiss323 @varsha-platogo everything currently looks good, great job. I've added a couple of comments that I think needs addressing

2024-04-16 07:53 UTC, majeed-platogo commented on src/android/Screenshot.java
>              if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
No need for the conditional statement here I think, just call `saveScreenshot` @attilakiss323

2024-04-16 07:53 UTC, majeed-platogo commented on src/android/ScreenshotSaver.java
> +                    Log.d(TAG, "Screenshot saved as: " + storageDir.getAbsolutePath());
I think we should remove the `Log.d` before merging

2024-04-16 14:51 UTC, majeed-platogo requested changes

2024-04-16 14:51 UTC, majeed-platogo commented on src/android/ScreenshotSaver.java
> +import android.util.Log;
@attilakiss323 small thing here, please remove unused import

2024-04-17 09:35 UTC, majeed-platogo approved these changes
Nice work @attilakiss323 @varsha-platogo

2024-04-17 12:33 UTC, merged